server:
  port: 9000
  servlet:
    context-path: /api/v1
  shutdown: graceful
  error:
    include-message:
      always

spring:
  application:
    jackson:
      default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html